build-rzg-ai-bsp.sh: Cherry-pick Poky basehash commit for RZ/G2L
We can avoid reparsing the same recipe by cherry-picking Poky commit
cfd897e213d, which prevents the following issue from occurring when
building the RZ/G2L{C} SDK:

ERROR: When reparsing *meta-environment.bb:do_generate_content, the
basehash value changed from x to y. The metadata is not deterministic and
this needs to be fixed.
ERROR: The following commands may help:
ERROR: $ bitbake meta-environment-smarc-rzg2l -cdo_generate_content -Snone
ERROR: Then:
ERROR: $ bitbake meta-environment-smarc-rzg2l -cdo_generate_content -Sprintdiff

Signed-off-by: Fabrizio Castro <fabrizio.castro.jz@renesas.com>
Signed-off-by: Ayman Chaudhry <ayman.chaudhry.kc@renesas.com>